### ISSUE TITLE
Trollius 2.0 cannot be installed on Python 2.6

### ISSUE THREAD

**Issue by haypo** [haypo/trollius#1]
Ben Darnell reported that Tornado build fails on Python 2.6 because of the wheel package. The wheel package was built using Python 2.7. Python 2.6 dependencies (orderreddict) are missing.

A solution would be to use environment markers on dependencies instead of using the Python version in setup.py.

A workaround is to not publish wheel packages: I removed it from PyPI for the release 2.0.

**Comment by vstinner** [comment]
I dropped support for Python 2.6 in the future version Trollius 2.1.
