### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by tirkarthi** [haypo/trollius#14]
The readthedocs link in GitHub project description and pypi page for the module returns 404.

Broken link :  https://trollius.readthedocs.org/

The .io link as part of the commit (https://github.com/vstinner/trollius/commit/0ce9dcbc0e14872558d6ad7aeb6c4e224e289756) is also broken

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately this project is not maintained and not expecting to make any changes. (The previous owner deliberately removed the docs to signal that this project is not maintained.)

**Comment by tirkarthi** [comment]
Thanks for the update. I understand about the project maintenance. Closing.
