### ISSUE TITLE
Truncated Exceptions in trollius 2.0 on python 2

### ISSUE THREAD

**Issue by imkin** [haypo/trollius#2]
I am referring to this issue.

https://bitbucket.org/enovance/trollius/issues/18/truncated-exception-tracebacks-on-python#comment-21503114

Since we moved to github I thought it would be good to have the issue here and also get to see if there is any update?

**Comment by imkin** [comment]
@haypo Any comments/updates?

**Comment by imkin** [comment]
https://github.com/haypo/trollius/compare/trollius...imkin:trollius

I have created a patch to export more of the exception stacktrace.

**Comment by vstinner** [comment]
It's fixed by f285592a7193e2e2a96af344efffb6dc8ad9836a if I understood correctly.
