### ISSUE TITLE
'__iter__' is not defined exception on Python 3.5 

### ISSUE THREAD

**Issue by matthewearl** [haypo/trollius#4]
Triggered on:

```
if compat.PY35:                                                            
    __await__ = __iter__ # make compatible with 'await' expression         
```

from the Future object in futures.py. Can be reproduced by running `import trollius` on Python 3.5.0. 

Seems to have been caused by 16b46b383ca84dcdc3aecc6ccf735499d497fef0 which uncomments out the offending line (which was commented out in 14d618e2959019c0c44191eea2481da76a8f0e72).

**Comment by vstinner** [comment]
I added an experimental support for Python 3.5 in the future version 2.1. Thanks for the bug report.

Sorry, I missed completly your bug report for an unknown reason :-/ I didn't get an email or it was lost by my mail filters.
